### PR TITLE
Fix range for detection of Illumina 1.5

### PR DESCRIPTION
**Pull request by cviner**
This fixes the range for detection of Illumina 1.5 format. Its quality score range was off-by-one in both directions:

- The score starts at ASCII 66 (`B`), which is the special code used for unknown qualities or from replacement of "read ends with a segment of mostly low quality (Q15 or below)" (per [Illumina](http://watson.nci.nih.gov/solexa/Using_SCSv2.6_15009921_A.pdf)).
- The score typically goes up to ASCII 105 (`i`), due to its starting from 3, since scores 0 and 1 are unused and 2 (`B`) is the special code. (I encountered numerous such base qualities with a collaborator's FASTQ data.)

This pull request continues from the previous PR #16, but is sufficiently independent that I felt it should be kept separate. Please let me know if you would prefer that I do otherwise.

### CODE REVIEW

**Comment by cviner** [comment]
I am not sure why this discussion appears duplicated here (may be a GitHub issue). #16 is the PR of record for this, and my final PR #20 and comment within 56d1a01 incorrectly referenced this PR and not #16.

**Comment by cviner** [comment]
Already sufficiently addressed by pull request #16 and its associated discussion.

**Comment by cviner** [comment]
On further inspection, these changes have not yet been merged in.

I welcome any additional feedback.

**Comment by brentp** [comment]
this seems ok, but can you fix the conflicts with current master?

**Comment by cviner** [comment]
@brentp Fixed—thanks! Please let me know if anything else is necessary.

**Comment by brentp** [comment]
cheers.

**Pull request merged**
